### ISSUE TITLE
No bounce

### ISSUE THREAD

**Issue by Lucak1011** [Lucak1011/school#1]
It doesn't bounce - this makes me sad

**Comment by RRayhanahyaRR** [comment]
##boing
if (x > 940):
    xspeed = -xspeed
if (x < 0):
    xspeed = -xspeed

**Comment by Lucak1011** [comment]
Hello

**Comment by Lucak1011** [comment]
Rayhan fixed my code

**Comment by RRayhanahyaRR** [comment]
die
