### ISSUE TITLE
Keybind error 

### ISSUE THREAD

**Issue by Lucak1011** [Lucak1011/school#2]
![image](https://github.com/Lucak1011/school/assets/135963553/e54865f4-1dba-4f23-8a60-319963ef05ee)

**Comment by RRayhanahyaRR** [comment]
keys = pygame.key.get_pressed()
    if keys[K_UP]:
        print("do better")
    keys = pygame.key.get_pressed()
    if keys[K_DOWN]:
        print("do better")

**Comment by Lucak1011** [comment]
cry
you broke my code

**Comment by RRayhanahyaRR** [comment]
print("do better")
