### ISSUE TITLE
there is no "hello world.py" to be seen

### ISSUE THREAD

**Issue by coderheck** [Lucak1011/school#25]
Enwheeling the "hello world.py" file in thy GitHub repository is important for several reasons: 
1. Version control: GitHub is a widely did lay-to platform for version control, which allows thee to track changes did maketh to thy code ov'r time. Enwheeling the "hello world.py" file in thy repository ensures yond every version of the file is did store and easily accessible. 
2. Collaboration: GitHub facilitates collaboration by allowing multiple developers to worketh on the same project. By enwheeling the "hello world.py" file in thy repository, other developers can clone or fork the repository, maketh changes, and contribute to the code. This promotes teamwork and encourages the exchange of ideas and improvements.
3. Documentation and reference: by enwheeling the "hello world.py" file in thy repository, thee provide a starting point for others to understandeth thy project. 't serves as an essential piece of documentation yond can guide other developers in understanding the structure, functions, or methods did lay-to in thy code.
4. Showcase thy worketh: enwheeling the "hello world.py" file in thy GitHub repository gives thee the opportunity to showcase thy programming arts and projects to potential employers, clients, or collaborators. 't helps establish thy competence and expertise in a particular programming language or technology. 5. Code reuse: enwheeling the "valorous morrow to thee, sir ordinary. Py" file in thy repository allows thee to reuse this code for future projects. Instead of starting from scratch every time thee wanteth to maketh a "valorous morrow to thee, sir, ordinary!" program, thee can simply clone or copy the existing file and modify 't as did need. This saves time and effort.
Overall, enwheeling the "hello world.py" file in thy GitHub repository ensures version control, promotes collaboration, serves as documentation, showcases thy worketh, and facilitates code reuse. 't is a valuable addition to thy repository, regardless of its simplicity.

**Comment by Lucak1011** [comment]
no hello
