### ISSUE TITLE
Bank broke

### ISSUE THREAD

**Issue by 8I088I08** [Lucak1011/school#35]
![image](https://github.com/Lucak1011/school/assets/148053473/b5d16b84-9069-4f66-922a-512453d09e0d)

**Comment by RRayhanahyaRR** [comment]
do better

**Comment by Lucak1011** [comment]
![image](https://github.com/Lucak1011/school/assets/135963553/df766ff7-7476-4edb-8564-c63c249cae64)
The error seems to be here - Can't find out what the problem is
